<Project>
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Identity.Web" Version="4.16.0" />
    <PackageVersion Include="Microsoft.Identity.Web.UI" Version="4.16.0" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="8.23.0" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
  </ItemGroup>
</Project>